// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Access is the golang structure of table access for DAO operations like Where/Data.
type Access struct {
	g.Meta    `orm:"table:access, do:true"`
	Id        interface{} //
	Debug     interface{} // 是否为调试表，只允许在开发环境使用，测试和线上环境禁用
	Name      interface{} // 实际表名，例如 apijson_user
	Alias     interface{} // 外部调用的表别名，例如 User
	Get       interface{} // 允许 get 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"] 用 JSON 类型不能设置默认值，反正权限对应的需求是明确的，也不需要自动转 JSONArray。
	Head      interface{} // 允许 head 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Gets      interface{} // 允许 gets 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Heads     interface{} // 允许 heads 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Post      interface{} // 允许 post 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Put       interface{} // 允许 put 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Delete    interface{} // 允许 delete 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	CreatedAt *gtime.Time // 创建时间
	Detail    interface{} //
}
