// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Request is the golang structure of table request for DAO operations like Where/Data.
type Request struct {
	g.Meta    `orm:"table:request, do:true"`
	Id        interface{} // 唯一标识
	Debug     interface{} // 是否为 DEBUG 调试数据，只允许在开发环境使用，测试和线上环境禁用：0-否，1-是。
	Version   interface{} // GET,HEAD可用任意结构访问任意开放内容，不需要这个字段。 其它的操作因为写入了结构和内容，所以都需要，按照不同的version选择对应的structure。  自动化版本管理： Request JSON最外层可以传  “version”:Integer 。 1.未传或 <= 0，用最新版。 “@order”:”version-“ 2.已传且 > 0，用version以上的可用版本的最低版本。 “@order”:”version+”, “version{}”:”>={version}”
	Method    interface{} // 只限于GET,HEAD外的操作方法。
	Tag       interface{} // 标签
	Structure interface{} // 结构。
	Detail    interface{} // 详细说明
	CreatedAt *gtime.Time //
}
