// =================================================================================
// This is auto-generated by GG CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/glennliao/apijson-go/apijson/internal/dao/internal"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// accessDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type accessDao struct {
	*internal.AccessDao
}

var (
	// Access is globally public accessible object for table  operations.
	Access = accessDao{
		internal.NewAccessDao(),
	}
)

func (d *accessDao) M(ctx context.Context) *gdb.Model {
	return d.Ctx(ctx).OmitNil().Batch(500)
}

func (d *accessDao) MC(ctx context.Context) (*gdb.Model, internal.AccessColumns) {
	return d.M(ctx), d.Columns()
}

func (d *accessDao) DMC(ctx context.Context) (*accessDao, *gdb.Model, internal.AccessColumns) {
	m := d.M(ctx)
	return d, m, d.Columns()
}

func (d *accessDao) WithRk(ctx context.Context, id ...string) *gdb.Model {
	m := d.M(ctx)
	if len(id) == 1 {
		return m.Where(d.RowKey(), id[0])
	}
	if len(id) == 0 {
		g.Log().Warning(ctx, "withRk is len0")
		return m.Where("1 = 2")
	}
	return m.WhereIn(d.RowKey(), id)
}

func (d *accessDao) RowKey() string {
	return d.Columns().Id
}

// Fill with you ideas below.
// #c045acc93408276887849c01956ec7c61ec6a566:021026:52
