### 单表查询
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "Todo": {

  }
}

### 单表列表查询1
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "Todo[]": {

  }
}

### 单表列表查询2
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "[]": {
    "Todo": {
      "@column": "id:todoId;title"
    },
    "page": 2,
    "count": 2

  }
}

### 双表关联查询
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "Todo": {

  },
  "User": {
    "id@": "Todo/userId"
  }
}

### 双表列表关联查询
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "[]": {
    "Todo": {

    },
    "User": {
      "id@": "[]/Todo/userId"
    }
  }
}

### 一对多
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "User": {},
  "[]": {
    "Todo": {
      "userId@": "User/id"
    }
  }
}

### 一对多数组关联查询
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "Todo": {
    "id": 1627794043692,
    "@column": "id,userId"
  },
  "User": {
    "id@": "Todo/userId",
    "@column": "id"
  },
  "[]": {
    "Todo": {
      "userId@": "Todo/userId",
      "@column": "id,userId"
    },
    "User": {
      "id@": "/Todo/userId",
      "@column": "id"
    }
  }
}


### 分页
POST http://127.0.0.1:8080/get
Content-Type: application/json

{
  "[]": {
    "todo": {
      "userId@": "todo/userId",
      "@column": "id,userId"
    },
    "user": {
      "id@": "/todo/userId",
      "@column": "id"
    }
  }
}

