// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Access is the golang structure for table access.
type Access struct {
	Id        uint        //
	Debug     int         // 是否为调试表，只允许在开发环境使用，测试和线上环境禁用
	Name      string      // 实际表名，例如 apijson_user
	Alias     string      // 外部调用的表别名，例如 User
	Get       string      // 允许 get 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"] 用 JSON 类型不能设置默认值，反正权限对应的需求是明确的，也不需要自动转 JSONArray。
	Head      string      // 允许 head 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Gets      string      // 允许 gets 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Heads     string      // 允许 heads 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Post      string      // 允许 post 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Put       string      // 允许 put 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	Delete    string      // 允许 delete 的角色列表，例如 ["LOGIN", "CONTACT", "CIRCLE", "OWNER"]
	CreatedAt *gtime.Time // 创建时间
	Detail    string      //
}
