// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Request is the golang structure for table request.
type Request struct {
	Id        int         // 唯一标识
	Debug     int         // 是否为 DEBUG 调试数据，只允许在开发环境使用，测试和线上环境禁用：0-否，1-是。
	Version   int         // GET,HEAD可用任意结构访问任意开放内容，不需要这个字段。 其它的操作因为写入了结构和内容，所以都需要，按照不同的version选择对应的structure。  自动化版本管理： Request JSON最外层可以传  “version”:Integer 。 1.未传或 <= 0，用最新版。 “@order”:”version-“ 2.已传且 > 0，用version以上的可用版本的最低版本。 “@order”:”version+”, “version{}”:”>={version}”
	Method    string      // 只限于GET,HEAD外的操作方法。
	Tag       string      // 标签
	Structure string      // 结构。
	Detail    string      // 详细说明
	CreatedAt *gtime.Time //
}
